###
GET http://localhost:8000/api/agendamentos/horarios/?data_agendamento=2023-10-20

###
POST http://localhost:8000/api/agendamentos/
Content-Type: application/json

{
  "data_agendamento": "2023-10-20T13:30:00",
  "nome_cliente": "Customer default",
  "email_cliente": "customer@email.com",
  "telefone_cliente": "123456789",
  "prestador": "bhigoreduardo"
}

###
GET http://localhost:8000/api/agendamentos/?username=bhigoreduardo
Authorization: Basic bhigoreduardo:admin

###
GET http://localhost:8000/api/agendamentos/2/?username=bhigoreduardo
Authorization: Basic bhigoreduardo:admin

###
PUT http://localhost:8000/api/agendamentos/2/
Content-Type: application/json
Authorization: Basic bhigoreduardo:admin

{
  "data_agendamento": "2023-08-30T23",
  "nome_cliente": "Nome",
  "email_cliente": "email@email.com",
  "telefone_cliente": "988309",
  "prestador": "bhigoreduardo"
}

###
PATCH http://localhost:8000/api/agendamentos/2/
Content-Type: application/json
Authorization: Basic bhigoreduardo:admin

{
  "nome_cliente": "Nome cliente"
}

###
DELETE http://localhost:8000/api/agendamentos/2/
Authorization: Basic bhigoreduardo:admin
