###
GET http://localhost:8000/api/agendamentos/horarios/?data_agendamento=2023-10-20

###
POST http://localhost:8000/api/agendamentos/
Content-Type: application/json

{
  "data_agendamento": "2023-10-20T10:30:00",
  "nome_cliente": "Customer default",
  "email_cliente": "customer@email.com",
  "telefone_cliente": "123456789"
}

###
GET http://localhost:8000/api/agendamentos/

###
GET http://localhost:8000/api/agendamentos/1/

###
PUT http://localhost:8000/api/agendamentos/1/
Content-Type: application/json

{
  "data_agendamento": "2023-08-30T23",
  "nome_cliente": "Nome",
  "email_cliente": "email@email.com",
  "telefone_cliente": "988309"
}

###
PATCH http://localhost:8000/api/agendamentos/1/
Content-Type: application/json

{
  "nome_cliente": "Nome cliente"
}

###
DELETE http://localhost:8000/api/agendamentos/1/